import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFE8B0',
    },
    scrollContent: {
        paddingBottom: 100,
        paddingHorizontal: 20,
        marginLeft:20,
        marginRight:20,
    },
    center: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    title: {
        fontSize: 37,
        fontWeight: '900',
        color: '#91483c',
        textAlign: 'center',
        marginBottom: 6,
        fontFamily: 'Fredoka',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingHorizontal: 10,
    },
    periodHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ffe599',
        paddingVertical: 10,
        borderRadius: 12,
        marginBottom: 20,
        borderWidth: 3,
        borderColor: '#eda82f',
    },
    navArrow: {
        fontSize: 28,
        color: '#91483c',
        fontWeight: 'bold',
        marginHorizontal: 16,
        fontFamily: 'Fredoka',
    },
    periodText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#91483c',
        fontFamily: 'Fredoka',
    },
    card: {
        backgroundColor: '#ffe599',
        padding: 20,
        borderRadius: 18,
        marginBottom: 16,
        borderWidth: 3,
        borderColor: '#eda82f',
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 4,
    },
    cardTouchable: {
        width: '100%',
    },
    cardTitle: {
        fontSize: 16,
        color: '#91483c',
        marginBottom: 6,
        fontFamily: 'Fredoka',
        textAlign: 'center',
    },
    cardValue: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#D45920',
        textAlign: 'center',
        fontFamily: 'Fredoka',
    },
    cardSubtitle: {
        fontSize: 16,
        color: '#91483c',
        textAlign: 'center',
        marginTop: 6,
        fontFamily: 'Fredoka',
    },
    chartContainer: {
        marginTop: 16,
        backgroundColor: '#FFF2CC',
        padding: 12,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#eda82f',
    },
    chartTitle: {
        fontWeight: 'bold',
        marginBottom: 8,
        color: '#91483c',
        fontSize: 16,
        fontFamily: 'Fredoka',
        textAlign: 'center',
    },
    section: {
        fontSize: 25,
        fontWeight: 'bold',
        color: '#52366b',
        marginTop: 24,
        marginBottom: 8,
        fontFamily: 'Fredoka',
    },
    categoryHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    categoryIcon: {
        width: 30,
        height: 30,
        marginRight: 10,
    },
    itemRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: '#FFF2CC',
        padding: 15,
        borderRadius: 12,
        borderColor: '#eda82f',
        borderWidth: 2,
        marginBottom: 10,
    },
    itemText: {
        fontSize: 18,
        color: '#52366b',
        fontFamily: 'Fredoka',
        flex: 1,
    },
    itemAmount: {
        fontSize: 18,
        fontWeight: '600',
        color: '#D45920',
        fontFamily: 'Fredoka',
    },
});