import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    section: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#2d3436',
        marginTop: 30,
        marginBottom: 12,
        backgroundColor: '#ffeaa7',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#fdcb6e',
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
    },
    categoryHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    categoryIcon: {
        width: 24,
        height: 24,
        marginRight: 10,
    },
    itemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        padding: 14,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#dfe6e9',
        marginBottom: 10,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
    },
    itemText: {
        fontSize: 16,
        color: '#2d3436',
        fontWeight: '600',
        flex: 1,
    },
    itemAmount: {
        fontSize: 16,
        color: '#2d3436',
        fontWeight: '600',
        width: 80,
        textAlign: 'right',
    },
    addSubBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 6,
        marginBottom: 20,
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: '#ffeaa7',
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#fdcb6e',
    },
    addSubText: {
        color: '#2d3436',
        fontWeight: 'bold',
        fontSize: 15,
        marginLeft: 8,
    },
    dropdownContainer: {
        zIndex: 2000,
        marginBottom: 14,
        marginTop: 4,
        backgroundColor: '#ffeaa7',
        borderRadius: 12,
        padding: 16,
        borderWidth: 2,
        borderColor: '#fdcb6e',
    },
    input: {
        flex: 1,
        borderWidth: 2,
        borderColor: '#fdcb6e',
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 10,
        fontSize: 16,
        backgroundColor: '#fff',
        color: '#2d3436',
        marginRight: 8,
    },
    inputTransparent: {
        borderWidth: 2,
        borderColor: '#fdcb6e',
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 10,
        fontSize: 16,
        backgroundColor: '#fff',
        marginTop: 10,
        color: '#2d3436',
    },
    button: {
        backgroundColor: '#6c5ce7',
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 16,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 6,
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    selectLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2d3436',
        marginBottom: 12,
    },
    subGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: 12,
        gap: 8,
    },
    subPill: {
        paddingVertical: 8,
        paddingHorizontal: 14,
        backgroundColor: '#f1f2f6',
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#b2bec3',
    },
    subPillActive: {
        backgroundColor: '#6c5ce7',
        borderColor: '#5a4bdc',
    },
    subPillText: {
        fontSize: 14,
        color: '#2d3436',
        fontWeight: '600',
    },
    subPillTextActive: {
        color: '#fff',
    },
    disabledText: {
        fontSize: 14,
        color: '#636e72',
        fontStyle: 'italic',
        textAlign: 'center',
        marginVertical: 10,
    },
    addIncomeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        padding: 14,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#dfe6e9',
        marginBottom: 20,
    },
    addButton: {
        backgroundColor: '#6c5ce7',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 6,
    },
    addButtonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    actionButton: {
        marginLeft: 10,
    },
});