import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    wrapper: {
        flex: 1,
        width: '100%',
    },
    container: {
        flex: 1,
        paddingHorizontal: 24,
        paddingTop: 50,
        paddingBottom: 40,
    },
    title: {
        fontSize: 40,
        fontWeight: '900',
        color: '#6B3E26',
        marginBottom: 20,
        marginTop: 50,
        textAlign: 'center',
        fontFamily: 'Fredoka',
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        backgroundColor: '#FFF',
        padding: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#F7C873',
    },
    icon: {
        width: 24,
        height: 24,
        marginRight: 12,
    },
    label: {
        flex: 1,
        fontSize: 16,
        color: '#5B3A1C',
        fontFamily: 'Fredoka',
    },
    input: {
        backgroundColor: '#FFF3DC',
        padding: 12,
        borderRadius: 8,
        width: 120,
        textAlign: 'right',
        fontSize: 16,
        color: '#5B3A1C',
        borderWidth: 1,
        borderColor: '#F7C873',
        fontFamily: 'Fredoka',
    },
    totalText: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#5B3A1C',
        textAlign: 'right',
        marginTop: 16,
        marginBottom: 24,
        fontFamily: 'Fredoka',
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 20,
        gap: 10,
        paddingHorizontal: 24,
    },
    button: {
        backgroundColor: '#91483C',
        padding: 15,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        flex: 1,
        height: 50,
    },
    backButton: {
        backgroundColor: '#f5f5f5',
        borderWidth: 1,
        borderColor: '#91483C',
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    backButtonText: {
        color: '#91483C',
    },
});
