import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        backgroundColor: '#FFE8B0',
    },
    title: {
        fontSize: 37,
        fontWeight: '900',
        color: '#91483c',
        textAlign: 'center',
        marginBottom: 6,
        fontFamily: 'Fredoka',
    },
    balance: {
        fontSize: 25,
        fontWeight: '600',
        color: '#cf6b04',
        textAlign: 'center',
        marginBottom: 20,
        fontFamily: 'Fredoka',
        letterSpacing: -0.7,
    },
    dateGroup: {
        marginBottom: 24,
        marginLeft: 30,
    },
    dateTitle: {
        fontSize: 25,
        fontWeight: 'bold',
        color: '#cc6a07',
        marginBottom: 12,
        fontFamily: 'Fredoka',
    },
    expenseBox: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#ffe599',
        borderRadius: 18,
        paddingVertical: 15,
        marginBottom: 10,
        borderWidth: 4,
        borderColor: '#eda82f',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
        paddingHorizontal: 10,
        marginRight: 27,
    },
    expenseLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    icon: {
        width: 50,
        height: 50,
        resizeMode: 'contain',
        marginRight: 8,
    },
    subcategory: {
        fontFamily: 'Fredoka',
        fontSize: 16,
        color: '#91483c',
    },
    sourceText: {
        fontFamily: 'Fredoka',
        fontSize: 12,
        color: '#666',
        marginTop: 2,
    },
    noteText: {
        fontFamily: 'Fredoka',
        fontSize: 12,
        color: '#666',
        marginTop: 2,
        fontStyle: 'italic',
    },
    subcategoryMultiline: {
        fontSize: 25,
        letterSpacing: -0.5,
        lineHeight: 22,
    },
    amountBlock: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    carrotImage: {
        width: 26,
        height: 26,
        resizeMode: 'contain',
        marginBottom: 2,
    },
    amountText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#D45920',
        fontFamily: 'Fredoka',
    },

    amountRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    carrotCoinText: {
        fontSize: 15,
        fontFamily: 'Fredoka',
        letterSpacing: -1.2,
        marginTop: 3,
        color: '#D45920',
    },
    addBtnWrapper: {
        position: 'absolute',
        bottom: 16,
        left: '13%',
    },
    addBtn: {
        width: 300,
        height: 70,
        backgroundColor: '#F56C3D',
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 6,
    },
    addBtnText: {
        color: '#fff',
        fontSize: 23,
        fontWeight: '500',
        fontFamily: 'Fredoka',
        marginLeft: 68,
    },
    bunnyIcon: {
        width: 90,
        height: 90,
        resizeMode: 'contain',
        position: 'absolute',
        top: -20,
        left: 10,
    },
    periodNavigation: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        marginTop: 10,
    },
    periodArrow: {
        padding: 10,
    },
    periodTitle: {
        flex: 1,
        alignItems: 'center',
    },
    periodText: {
        fontSize: 14,
        color: '#91483c',
        fontWeight: '500',
        marginTop: 2,
    },
});
