import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFE8B0',
        padding: 20,
    },
    fixedHeader: {
        paddingHorizontal: 20,
        paddingTop: 10,
    },
    headerContent: {
        paddingBottom: 15,
    },
    title: {
        fontSize: 37,
        fontWeight: '900',
        fontFamily: 'Fredoka',
        color: '#91483c',
        textAlign: 'center',
        marginBottom: 6,
    },
    balance: {
        fontSize: 25,
        fontWeight: '600',
        color: '#cf6b04',
        textAlign: 'center',
        marginBottom: 20,
        fontFamily: 'Fredoka',
        letterSpacing: -0.7,
    },
    scrollView: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 100,
        marginRight:20,
        marginLeft:20,
    },
    calendarWrapper: {
        backgroundColor: '#fff5d6',
        borderRadius: 20,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
        marginLeft:30,
        marginRight: 30,
    },
    calendar: {
        borderRadius: 15,
        overflow: 'hidden',
    },
    dayContainer: {
        width: 36,
        height: 36,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    iconContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    dayNumber: {
        fontSize: 13,
        fontFamily: 'Fredoka',
        color: '#6d3d00',
        position: 'relative',
        bottom: 25,

    },
    dayIcon: {
        width: 37,
        height: 37,
        position: 'absolute',
    },
    legendContainer: {
        backgroundColor: '#ffe599',
        borderRadius: 20,
        padding: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
        marginLeft: 30,
        marginRight: 30,
    },
    legendTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        fontFamily: 'Fredoka',
        color: '#52366b',
        marginBottom: 15,
        marginLeft: 15,
    },
    legendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
       paddingHorizontal: 10,
    },
    legendIcon: {
        width: 50,
        height: 50,
        marginRight: 12,
    },
    legendText: {
        fontSize: 16,
        fontFamily: 'Fredoka',
        color: '#3D405B',
        flex: 1,
    },
});