import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        padding: 24,
        backgroundColor: '#FFF5E5',
        flexGrow: 1,
    },
    title: {
        fontSize: 32,
        fontFamily: 'Fredoka',
        color: '#6A4C93',
        marginBottom: 24,
        textAlign: 'center',
    },
    avatar: {
        width: 110,
        height: 110,
        borderRadius: 55,
        alignSelf: 'center',
        marginBottom: 12,
        borderWidth: 3,
        borderColor: '#F19953',
    },
    avatarBtn: {
        alignSelf: 'center',
        backgroundColor: '#F19953',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 30,
        marginBottom: 20,
        borderWidth: 2,
        borderColor: '#000',
    },
    avatarBtnText: {
        color: '#000',
        fontWeight: 'bold',
        fontSize: 16,
        fontFamily: 'Fredoka',
    },
    input: {
        backgroundColor: '#fff',
        padding: 14,
        borderRadius: 14,
        borderWidth: 2,
        borderColor: '#000',
        marginBottom: 14,
        fontFamily: 'Fredoka',
        fontSize: 16,
        color: '#2C2C2C',
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#E07A5F',
        marginTop: 24,
        marginBottom: 12,
        fontFamily: 'Fredoka',
    },
    switchRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
    },
    itemBtn: {
        backgroundColor: '#F4F1DE',
        paddingVertical: 14,
        borderRadius: 18,
        paddingHorizontal: 20,
        marginTop: 20,
        borderWidth: 2,
        borderColor: '#000',
    },
    itemBtnText: {
        fontSize: 16,
        fontFamily: 'Fredoka',
        color: '#2C2C2C',
    },
    saveBtn: {
        backgroundColor: '#00B894',
        paddingVertical: 16,
        borderRadius: 40,
        alignItems: 'center',
        marginTop: 28,
        borderWidth: 2,
        borderColor: '#000',
    },
    saveBtnText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 18,
        fontFamily: 'Fredoka',
    },
    logoutBtn: {
        backgroundColor: '#D62828',
        paddingVertical: 16,
        borderRadius: 40,
        alignItems: 'center',
        marginTop: 16,
        borderWidth: 2,
        borderColor: '#000',
    },
    logoutText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 18,
        fontFamily: 'Fredoka',
    },
    dropdown: {
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#000',
        marginBottom: 16,
        backgroundColor: '#FFF',
    },
});