import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
    },
    scrollContent: {
        padding: 20,
        paddingBottom: 40,
    },
    title: {
        fontSize: 28,
        fontWeight: '900',
        fontFamily: 'Fredoka',
        color: '#91483c',
        textAlign: 'center',
        marginBottom: 20,
    },
    avatarContainer: {
        alignItems: 'center',
        marginBottom: 20,
    },
    avatar: {
        width: 120,
        height: 120,
        borderRadius: 60,
        borderWidth: 3,
        borderColor: '#d5790d',
    },
    formContainer: {
        backgroundColor: '#fff5d6',
        borderRadius: 20,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
    },
    input: {
        backgroundColor: '#ffe8b0',
        padding: 15,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#d5790d',
        marginBottom: 15,
        fontFamily: 'Fredoka',
        fontSize: 16,
        color: '#2d3436',
    },
    disabledInput: {
        backgroundColor: '#f0f0f0',
        color: '#999',
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        fontFamily: 'Fredoka',
        color: '#52366b',
        marginTop: 15,
        marginBottom: 15,
    },
    switchRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    switchLabel: {
        fontFamily: 'Fredoka',
        fontSize: 16,
        color: '#2d3436',
    },
    changePasswordBtn: {
        backgroundColor: '#ffe599',
        padding: 15,
        borderRadius: 12,
        marginBottom: 15,
        borderWidth: 2,
        borderColor: '#d5790d',
        alignItems: 'center',
    },
    changePasswordText: {
        fontFamily: 'Fredoka',
        fontSize: 16,
        color: '#2d3436',
        fontWeight: '600',
    },
    passwordChangeContainer: {
        marginBottom: 15,
    },
    passwordButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
    },
    cancelBtn: {
        backgroundColor: '#ffe599',
        padding: 12,
        borderRadius: 12,
        flex: 1,
        marginRight: 10,
        borderWidth: 2,
        borderColor: '#d5790d',
        alignItems: 'center',
    },
    cancelBtnText: {
        fontFamily: 'Fredoka',
        fontSize: 16,
        color: '#2d3436',
        fontWeight: '600',
    },
    savePasswordBtn: {
        backgroundColor: '#00B894',
        padding: 12,
        borderRadius: 12,
        flex: 1,
        borderWidth: 2,
        borderColor: '#007a63',
        alignItems: 'center',
    },
    savePasswordBtnText: {
        fontFamily: 'Fredoka',
        fontSize: 16,
        color: 'white',
        fontWeight: 'bold',
    },
    itemBtn: {
        backgroundColor: '#ffe599',
        padding: 15,
        borderRadius: 12,
        marginTop: 15,
        borderWidth: 2,
        borderColor: '#d5790d',
        alignItems: 'center',
    },
    itemBtnText: {
        fontFamily: 'Fredoka',
        fontSize: 16,
        color: '#2d3436',
        fontWeight: '600',
    },
    saveBtn: {
        backgroundColor: '#00B894',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 20,
        borderWidth: 2,
        borderColor: '#007a63',
    },
    saveBtnText: {
        fontFamily: 'Fredoka',
        fontSize: 18,
        color: 'white',
        fontWeight: 'bold',
    },
    deleteAccountBtn: {
        backgroundColor: '#ffe599',
        padding: 15,
        borderRadius: 12,
        marginTop: 15,
        borderWidth: 2,
        borderColor: '#d5790d',
        alignItems: 'center',
    },
    deleteAccountText: {
        fontFamily: 'Fredoka',
        fontSize: 16,
        color: '#D62828',
        fontWeight: '600',
    },
    deleteConfirmationContainer: {
        backgroundColor: '#ffe8b0',
        padding: 15,
        borderRadius: 12,
        marginTop: 15,
        borderWidth: 2,
        borderColor: '#d5790d',
    },
    deleteConfirmationText: {
        fontFamily: 'Fredoka',
        fontSize: 16,
        color: '#2d3436',
        textAlign: 'center',
        marginBottom: 15,
    },
    deleteButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    cancelDeleteBtn: {
        backgroundColor: '#ffe599',
        padding: 12,
        borderRadius: 12,
        flex: 1,
        marginRight: 10,
        borderWidth: 2,
        borderColor: '#d5790d',
        alignItems: 'center',
    },
    cancelDeleteBtnText: {
        fontFamily: 'Fredoka',
        fontSize: 16,
        color: '#2d3436',
        fontWeight: '600',
    },
    confirmDeleteBtn: {
        backgroundColor: '#D62828',
        padding: 12,
        borderRadius: 12,
        flex: 1,
        borderWidth: 2,
        borderColor: '#9e1e1e',
        alignItems: 'center',
    },
    confirmDeleteBtnText: {
        fontFamily: 'Fredoka',
        fontSize: 16,
        color: 'white',
        fontWeight: 'bold',
    },
    logoutBtn: {
        backgroundColor: '#D62828',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 15,
        borderWidth: 2,
        borderColor: '#9e1e1e',
    },
    logoutText: {
        fontFamily: 'Fredoka',
        fontSize: 18,
        color: 'white',
        fontWeight: 'bold',
    },
    nameHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    nameText: {
        fontSize: 24,
        fontFamily: 'Fredoka',
        fontWeight: 'bold',
        color: '#52366b',
    },
    editButton: {
        color: '#d5790d',
        fontFamily: 'Fredoka',
        fontWeight: '600',
        fontSize: 16,
    },
    infoContainer: {
        marginBottom: 15,
    },
    infoLabel: {
        fontFamily: 'Fredoka',
        fontSize: 14,
        color: '#6d3d00',
        marginBottom: 2,
    },
    infoValue: {
        fontFamily: 'Fredoka',
        fontSize: 16,
        color: '#2d3436',
        fontWeight: '600',
        marginBottom: 10,
        padding: 12,
        backgroundColor: '#ffe8b0',
        borderRadius: 8,
    },
    bankConnectBtn: {
        backgroundColor: '#4CAF50',
        padding: 15,
        borderRadius: 10,
        marginVertical: 15,
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#388E3C',
    },
    bankConnectBtnText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
    },
    disconnectBtn: {
        backgroundColor: '#D62828',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 15,
        borderWidth: 2,
        borderColor: '#9e1e1e',
    },
    disconnectBtnText: {
        fontFamily: 'Fredoka',
        fontSize: 18,
        color: 'white',
        fontWeight: 'bold',
    },
    bankBtn: {
        backgroundColor: '#D62828',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 15,
        borderWidth: 2,
        borderColor: '#9e1e1e',
    },

    // Badge Section
    badgeSection: {
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        borderRadius: 20,
        padding: 20,
        marginHorizontal: 20,
        marginBottom: 16,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    badgeTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#91483C',
        marginBottom: 16,
        fontFamily: 'Fredoka',
        textAlign: 'center',
    },
    badgeStats: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: 20,
    },
    badgeStat: {
        alignItems: 'center',
    },
    badgeStatNumber: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#91483C',
        fontFamily: 'Fredoka',
    },
    badgeStatLabel: {
        fontSize: 12,
        color: '#666',
        fontFamily: 'Fredoka',
        marginTop: 2,
    },
    earnedBadgesContainer: {
        marginBottom: 20,
    },
    earnedBadgesTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#91483C',
        marginBottom: 12,
        fontFamily: 'Fredoka',
    },
    upcomingBadgesContainer: {
        marginBottom: 20,
    },
    upcomingBadgesTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#91483C',
        marginBottom: 12,
        fontFamily: 'Fredoka',
    },
    badgeGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    earnedBadge: {
        backgroundColor: '#FFF3E0',
        borderRadius: 16,
        padding: 12,
        alignItems: 'center',
        width: '30%',
        borderWidth: 2,
        borderColor: '#FF8F00',
    },
    unearnedBadge: {
        backgroundColor: '#F5F5F5',
        borderRadius: 16,
        padding: 12,
        alignItems: 'center',
        width: '30%',
        borderWidth: 2,
        borderColor: '#E0E0E0',
    },
    badgeEmoji: {
        fontSize: 32,
        marginBottom: 4,
    },
    unearnedEmoji: {
        opacity: 0.3,
    },
    badgeName: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#91483C',
        textAlign: 'center',
        fontFamily: 'Fredoka',
        marginBottom: 2,
    },
    badgeDesc: {
        fontSize: 10,
        color: '#666',
        textAlign: 'center',
        fontFamily: 'Fredoka',
    },
    badgeRequirement: {
        fontSize: 10,
        color: '#666',
        textAlign: 'center',
        fontFamily: 'Fredoka',
    },
});
