import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 50,
    paddingBottom: 80,
  },
  title: {
    fontSize: 40,
    fontWeight: '900',
    color: '#6B3E26',
    textAlign: 'center',
    marginBottom: 10,
    fontFamily: 'Fredoka',
  },
  subtitle: {
    fontSize: 18,
    color: '#7C4F29',
    textAlign: 'center',
    marginBottom: 24,
    fontFamily: 'Fredoka',
  },
  highlightText: {
    color: '#c28619',
    fontWeight: 'bold',
    fontSize: 20,
    marginBottom: 20,
    textAlign: 'center',
    fontFamily: 'Fredoka',
  },
  sectionTitle: {
    marginTop: 26,
    backgroundColor: '#FFE49D',
    borderLeftWidth: 6,
    borderLeftColor: '#FFD366',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    fontSize: 20,
    fontWeight: 'bold',
    color: '#5B3A1C',
    fontFamily: 'Fredoka',
  },
  itemText: {
    fontSize: 16,
    color: '#4A3B2D',
    marginLeft: 14,
    marginBottom: 4,
    fontFamily: 'Fredoka',
  },
  categoryTitle: {
    fontSize: 17,
    color: '#3E2F22',
    fontWeight: 'bold',
    marginTop: 12,
    marginLeft: 12,
    fontFamily: 'Fredoka',
  },
  subItemText: {
    fontSize: 15,
    color: '#5A4633',
    marginLeft: 26,
    marginBottom: 2,
    fontFamily: 'Fredoka',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 40,
    gap: 16,
  },
  button: {
    flex: 1,
    backgroundColor: '#FFA94D',
    padding: 16,
    borderRadius: 22,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 5,
  },
  backButton: {
    backgroundColor: '#FFE49D',
  },
  buttonText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFF',
    fontFamily: 'Fredoka',
  },
  backButtonText: {
    color: '#6B3E26',
  },
});
